-- Initial brands with an accent color each. Editable from the admin panel.
INSERT OR IGNORE INTO brands (name, slug, accent_color, sort_order) VALUES
    ('Ferrari',              'ferrari',              '#D40000', 10),
    ('Porsche',              'porsche',              '#B8860B', 20),
    ('Lamborghini',          'lamborghini',          '#C9A227', 30),
    ('McLaren',              'mclaren',              '#FF8000', 40),
    ('Mercedes-Benz',        'mercedes-benz',        '#6B7280', 50),
    ('BMW',                  'bmw',                  '#1C69D4', 60),
    ('Audi',                 'audi',                 '#BB0A30', 70),
    ('Volkswagen',           'volkswagen',           '#001E50', 80),
    ('Nissan',               'nissan',               '#C3002F', 90),
    ('Toyota',               'toyota',               '#EB0A1E', 100),
    ('Honda',                'honda',                '#CC0000', 110),
    ('Mazda',                'mazda',                '#101010', 120),
    ('Subaru',               'subaru',               '#013C74', 130),
    ('Mitsubishi',           'mitsubishi',           '#E60012', 140),
    ('Ford',                 'ford',                 '#003478', 150),
    ('Chevrolet',            'chevrolet',            '#CD9834', 160),
    ('Dodge',                'dodge',                '#BA0C2F', 170),
    ('Plymouth',             'plymouth',             '#5B2C83', 180),
    ('Jeep',                 'jeep',                 '#4B5320', 190),
    ('Aston Martin',         'aston-martin',         '#00665E', 200),
    ('Bugatti',              'bugatti',              '#1B3F8B', 210),
    ('Koenigsegg',           'koenigsegg',           '#F2A900', 220),
    ('Pagani',               'pagani',               '#3D3D3D', 230),
    ('Lotus',                'lotus',                '#005C3C', 240),
    ('Jaguar',               'jaguar',               '#2E3B32', 250),
    ('Alfa Romeo',           'alfa-romeo',           '#8F0C25', 260),
    ('Maserati',             'maserati',             '#0C2340', 270),
    ('Tesla',                'tesla',                '#CC0000', 280),
    ('DeLorean',             'delorean',             '#8A9097', 290),
    ('Volvo',                'volvo',                '#1F3A60', 300),
    ('Originales / Fantasía','originales-fantasia',  '#1F4BFF', 999);
