<?php

/**
 * GARAGE configuration template.
 *
 * Copy to app/config.php for local development. In production app/config.php is
 * generated by the GitHub Actions workflow from repository Secrets and is never
 * committed. Keep secrets out of this file.
 */

return [
    'app' => [
        // 'production' hides errors from visitors and logs them instead.
        'env'       => 'local',
        // Public URL of the app, no trailing slash.
        'url'       => 'http://localhost:8090/garage',
        // URL path where the app is mounted. '' if served from the domain root.
        'base_path' => '/garage',
        // Random string (64+ hex chars) used to HMAC visitor IPs for rate limiting.
        'key'       => 'change-me-to-a-long-random-string',
        'timezone'  => 'America/Mexico_City',
    ],

    'db' => [
        'host'    => 'db',
        'port'    => 3306,
        'name'    => 'garage',
        'user'    => 'garage',
        'pass'    => '',
        'charset' => 'utf8mb4',
    ],

    'admin' => [
        // Output of password_hash(). Set it with: php bin/set-password.php
        // The plain password never lives on the server or in the repo.
        'password_hash'   => '',
        // Owner session lifetime (inactivity), in seconds.
        'session_ttl'     => 1800,
        // Failed password attempts allowed per real IP within the window.
        'max_attempts'    => 5,
        'attempt_window'  => 900,
    ],

    'session' => [
        // true in production (Cloudflare serves HTTPS even though the origin sees HTTP).
        'secure' => false,
    ],

    // Token required by POST /_migrate (header X-Migrate-Token). Empty disables the endpoint.
    'migrate_token' => '',

    'mail' => [
        'host'       => 'localhost',
        'port'       => 587,
        'secure'     => 'tls',
        'verify_tls' => false,
        'username'   => 'contacto@samueltorres.dev',
        'password'   => '',
        'from_email' => 'contacto@samueltorres.dev',
        'from_name'  => 'GARAGE',
        'notify_to'  => 'samuelt@conqr.mx',
    ],

    'cpanel' => [
        'host'  => '',
        'user'  => '',
        'token' => '',
    ],
];
